import Head from "next/head"
import List from "../components/list"

export default function Home() {
  return (
    <>
      <Head>
        <title>Soccer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-4 gap-4">
        <div className="col-start-1 col-end-5">
          <List />
        </div>
      </main>
    </>
  )
}
