import Head from "next/head"
import List from "../components/list"

export default function Home() {
  return (
    <>
      <Head>
        <title>Soccer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <List />
      </main>
    </>
  )
}
